-- Q1. What is the total revenue generated by male vs female custromer?
SELECT gender, sum(purchase_amount) as Revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used discount and still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer 
WHERE discount_applied ='YES' 	AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with highest average review raitng?
SELECT item_purchased, avg(review_rating) as product_rating
FROM customer
GROUP BY item_purchased
ORDER BY product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, avg(purchase_amount) as avg_purchase_amount
FROM customer
WHERE shipping_type in ("standard","express")
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between ubscribers and non-subscribers.
SELECT subscription_status,count(customer_id) as total_customers, avg(purchase_amount) as avg_spent, sum(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
round(sum(CASE WHEN discount_applied = "yes" THEN 1 ELSE 0 END)*100 /count(*),2) as discount_rates
FROM customer
GROUP BY item_purchased
ORDER BY discount_rates DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type as (
select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN "NEW"
WHEN previous_purchases BETWEEN 2 AND 10 THEN "RETURNNG"
ELSE "LOYAL" END as customer_segment
FROM customer)
SELECT customer_segment, count(*)
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category
WITH item_counts as (
SELECT category,item_purchased,count(customer_id) as purchase_count,
ROW_NUMBER() OVER(partition by category order by count(customer_id) DESC) as item_ranks
FROM customer
GROUP BY category,item_purchased)
SELECT item_ranks,category, item_purchased,purchase_count
FROM item_counts
WHERE item_ranks <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases >= 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, sum(purchase_amount) as revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;



   
